version: '2'

services:
  dmall-inventory-service:
    image: '${DMALL_DOCKER_REGISTRY}/dmall/inventory-service:${BUILD_NUMBER}'
    ports:
      - "8082:8082"
    external_links:
      - dmall-config-server/dmall-config-server:dmall-config-server
      - dmall-registry-server/dmall-registry-server:dmall-registry-server