version: '2'

services:
  dmall-inventory-service:
    image: ec2-54-223-92-91.cn-north-1.compute.amazonaws.com.cn:5000/dmall/inventory-service:$BUILD_NUMBER
    ports:
      - "8082:8082"
    networks:
          - jenkins_dmall-network
    container_name: dmall-inventory-service
networks:
  jenkins_dmall-network:
    external: true